In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [2]:
df= pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [6]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [7]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [8]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [9]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
df = pd.get_dummies(df, columns=['Geography','Gender'],drop_first=True)
# basically it converts the names in a column as 0 or 1 there are 3 in geography spain france germany 
# so it makes 3 columns and the first one is dropped

In [11]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [12]:
X=df.drop(columns=['Exited'])
y=df['Exited']
# X contains all columns except Exited
# y contains only the Exited column means the thing you want to predict 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=1)
# random_state ensures the same random split every time for reproducibility

In [13]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,False,False,False

In [14]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [15]:
X_train.shape

(8000, 11)

In [22]:
from sklearn.preprocessing import StandardScaler
# importing the standard scalar class
scaler = StandardScaler()
# creating an obj of the standard scalar class
scaler.fit(X_train)
# we get to know what the values are like 
# calculates and store the mean and standard deviation across all columns 
X_train_scaled = scaler.transform(X_train)
# now transformation using the formula stored in the variable
X_test_scaled = scaler.transform(X_test)

# we learn from training but transform both train and test data

In [24]:
scaler.mean_

array([6.50313625e+02, 3.88872500e+01, 5.02500000e+00, 7.64634433e+04,
       1.53187500e+00, 7.07000000e-01, 5.11500000e-01, 1.00143430e+05,
       2.53750000e-01, 2.47000000e-01, 5.44250000e-01])

In [25]:
scaler.scale_
# standard deviation

array([9.66709471e+01, 1.04682395e+01, 2.88567583e+00, 6.23686450e+04,
       5.83510055e-01, 4.55138440e-01, 4.99867733e-01, 5.75712856e+04,
       4.35156222e-01, 4.31266739e-01, 4.98038088e-01])

In [17]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [27]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [29]:
model = Sequential()

# here we will be doing 1 input 1 hidden- 3 perceptron 

# input layer + hidden layer 
model.add(Dense(3,activation='sigmoid',input_dim=11))
model.add(Dense(1,activation='sigmoid'))

In [35]:
model.summary()
# gives a summary of our model

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.compile(loss='binary_crossentropy',optimizer='Adam')
# adam generally works better

In [42]:
model.fit(X_train_scaled,y_train,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4381
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4435
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4288
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4356
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4299
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4296
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4139
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4248
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4265
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4164

In [43]:
# now the model has all thhe wrights and biases 
model.layers[0].get_weights()
# for thhe first layer these are the weights and the last line has the biases

[array([[ 1.5347798e-01, -1.4276843e-01,  1.3812162e-01],
        [-2.1305707e+00,  6.6485703e-02,  2.3364491e+00],
        [ 1.3929035e-02, -2.7317613e-01,  9.2642918e-02],
        [-3.0933198e-01, -2.5706839e-02,  6.7124359e-02],
        [-3.5701976e-03, -1.7307997e+00,  1.3335140e-01],
        [-7.2264209e-02, -2.1236725e-01, -1.3552727e-01],
        [ 7.5493056e-01, -1.1344937e+00, -4.7982588e-01],
        [-2.8263629e-04,  3.2105073e-02,  1.9419961e-01],
        [-6.2487352e-01,  3.7177056e-01,  7.1864611e-01],
        [-1.3076062e-02,  2.9894823e-02,  7.3217512e-03],
        [ 6.4933854e-01, -2.2989497e-01, -1.6300173e-01]], dtype=float32),
 array([ 0.880757 , -0.9330929, -0.4689964], dtype=float32)]

In [44]:
# now the model has all thhe wrights and biases 
model.layers[1].get_weights()
#

[array([[-1.9834911],
        [ 0.5950521],
        [ 0.6833479]], dtype=float32),
 array([-0.85020727], dtype=float32)]

In [45]:
# now prediction portion 
model.predict(X_test_scaled)
# noww since we are using sigmoid its givinga probability 
# to tranform into binary 
# we just give a threshold here 
# 0.5 is the threshold <0.5 customer leaves >0.5 customer stays

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[0.1215926 ],
       [0.12126172],
       [0.12114409],
       ...,
       [0.06251458],
       [0.09433795],
       [0.4382286 ]], dtype=float32)

In [46]:
y_log=model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [49]:
y_pred=np.where(y_log>0.5,1,0)
# where y_log is >0.5 output 1 else outputt 0

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
# actual data and predicted data

0.8195

In [ ]:
# now i will be experimenmting to increase accuracy